spring.application.name=ApiGateway
server.port=9090

spring.cloud.gateway.default-filters=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*

spring.cloud.discovery.enabled=true
spring.cloud.gateway.routes[0].id= FLIGHTDETAILS
spring.cloud.gateway.routes[0].uri= lb://FLIGHTDETAILS
spring.cloud.gateway.routes[0].predicates[0]=Path= /flights/**
spring.cloud.gateway.routes[0].filters=AuthenticationFilter

spring.cloud.gateway.routes[1].id= SEARCHMICROSERVICE	
spring.cloud.gateway.routes[1].uri= lb://SEARCHMICROSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path= /search/**

spring.cloud.gateway.routes[2].id= BOOKING	
spring.cloud.gateway.routes[2].uri= lb://BOOKING
spring.cloud.gateway.routes[2].predicates[0]=Path= /booking/**,/passenger/**
spring.cloud.gateway.routes[2].filters=AuthenticationFilter

spring.cloud.gateway.routes[3].id= CHECKIN	
spring.cloud.gateway.routes[3].uri= lb://CHECKIN
spring.cloud.gateway.routes[3].predicates[0]=Path= /checkin/**
spring.cloud.gateway.routes[3].filters=AuthenticationFilter

spring.cloud.gateway.routes[4].id= FLIGHTSECURITY	
spring.cloud.gateway.routes[4].uri= lb://FLIGHTSECURITY
spring.cloud.gateway.routes[4].predicates[0]=Path= /auth/**

springdoc.enable-native-support=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[0].name=API Gateway Service
springdoc.swagger-ui.urls[1].url=/flights/v3/api-docs
springdoc.swagger-ui.urls[1].name=FlightDetail Service
springdoc.swagger-ui.urls[2].url=/search/v3/api-docs
springdoc.swagger-ui.urls[2].name=Search Service
springdoc.swagger-ui.urls[3].url=/booking/v3/api-docs
springdoc.swagger-ui.urls[3].name=Booking Service
springdoc.swagger-ui.urls[4].url=/checkin/v3/api-docs
springdoc.swagger-ui.urls[4].name=Checkin Service
