spring.application.name=Booking
server.port=8083
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=Bookings

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

openapi.service.title=Booking Service
openapi.service.version=1.0.0
openapi.service.url=http://localhost:9090

springdoc.swagger-ui.path=/booking/swagger-ui.html
springdoc.api-docs.path=/booking/v3/api-docs
logging.file.name=loggers.log