spring.application.name=CheckIn

server.port=8084
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=Bookings

eureka.client.serverUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

openapi.service.title=Checkin Service
openapi.service.version=1.0.0
openapi.service.url=http://localhost:9090


springdoc.swagger-ui.path=/checkin/swagger-ui.html
springdoc.api-docs.path=/checkin/v3/api-docs
logging.file.name=loggers.log